#! /bin/sh

set -e

case "$1" in
start)
    echo -n "Starting simswitch: "
    start-stop-daemon -S -b -a /usr/bin/simswitch
    echo "done"
    ;;
  stop)
    echo -n "Stopping simswitch: "
    start-stop-daemon -K -n simswitch
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage simswitch{ start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
